API:
  API_KEY: 567d545284e79fd028d25c51d2819c1321bae3403df833a1c63e06f725eeb3df
  BASE_URL: https://api.together.xyz
  LARGE_LOGICAL_MODEL: meta-llama/Llama-3-70b-chat-hf
  LOGICAL_MODEL: meta-llama/Llama-3-70b-chat-hf
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT: ./raw_text_input_vision_paper
  OUTPUT: ./output
  PROMPTS: ./prompts_vision_paper
SYSTEM:
  CHUNK_SIZE: 1900
  COMPLETION_MODE: false
  CONCURRENCY_LIMIT: 60
  DOUBLE_CHECK_COUNTER: 3
  FINAL_ASSISTANT_PROMPT_NO_RAG: You are a crypto expert AI and a member of the Verus
    community, with specialized knowledge about the Verus multi-chain and multi-currency
    blockchain protocol, as well as an understanding of crypto in general. Use your
    knowledge to help questioners understand more about Verus.
  FINAL_ASSISTANT_PROMPT_RAG: 'You are a crypto expert AI and a member of the Verus
    community, with specialized knowledge about the Verus multi-chain and multi-currency
    blockchain protocol, as well as an understanding of crypto in general. Use your
    knowledge and the provided context to help questioners understand more about Verus.
    Context information is below.

    --------------------

    {data}'
  MODE: api
  STOP: true
  SUBSET_SIZE: 10
  USE_SUBSET: true
