API:
  API_KEY: d43b49fe624928487f9af975f3ffca53b89a96019e5c602fad0e45caeb1f4a9b
  BASE_URL: https://api.together.xyz
  LARGE_LOGICAL_MODEL: meta-llama/Llama-3-70b-chat-hf
  LOGICAL_MODEL: meta-llama/Llama-3-70b-chat-hf
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT: ./raw_text_input_wiki
  OUTPUT: ./output
  PROMPTS: ./prompts
SYSTEM:
  CHUNK_SIZE: 1900
  COMPLETION_MODE: false
  CONCURRENCY_LIMIT: 60
  DOUBLE_CHECK_COUNTER: 3
  FINAL_ASSISTANT_PROMPT_NO_RAG: |
    You are a crypto expert AI and a member of the Verus community, with specialized knowledge about the Verus multi-chain and multi-currency blockchain protocol, as well as an understanding of crypto in general. Use your knowledge to help questioners understand more about Verus.

    **Background:**
    
  FINAL_ASSISTANT_PROMPT_RAG: |
    You are a crypto expert AI and a member of the Verus community, with specialized knowledge about the Verus multi-chain and multi-currency blockchain protocol, as well as an understanding of crypto in general. Use your knowledge and the provided context to help questioners understand more about Verus. Context information is below.

    --------------------

    {data}
  MODE: api
  STOP: true
  SUBSET_SIZE: 10
  USE_SUBSET: true